/**
 * Ambient declarations.
 *
 * GObject introspection types come from the `@girs` stubs, generated by
 * `npm run types` inside the dev shell and listed in `tsconfig.json`. They are
 * gitignored for their size -- twenty-odd megabytes of generated declarations
 * -- rather than for being machine-specific: they carry no store paths and the
 * script reproduces them exactly.
 */

/**
 * AGS compiles SCSS through dart-sass as part of the build. `ags run` resolves
 * the import to a path on disk, `ags bundle` inlines the compiled CSS, and
 * `App.apply_css` accepts either form.
 */
declare module "*.scss" {
  const css: string
  export default css
}

declare module "*.css" {
  const css: string
  export default css
}

/** Set by the AGS bundler via `-d "SRC=..."`; the installed data directory. */
declare const SRC: string
