#!/usr/bin/env bash
# Regenerate src/data/emoji.ts from the Unicode emoji test file.
#
# The list has to be in the source tree rather than read at runtime: the shell
# is a bundled script with no data directory of its own, and a lock screen of a
# launcher that only works when some other package happens to be installed is
# not worth having. It is generated rather than typed out so that a Unicode
# release is a one-command update.
#
# Usage: tools/generate-emoji.sh [path/to/emoji-test.txt]
#
# With no argument the file comes from nixpkgs, which is where the version in
# the generated header comes from too.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/src/data/emoji.ts"

if [ $# -ge 1 ]; then
  source_file="$1"
else
  store="$(nix build --no-link --print-out-paths nixpkgs#unicode-emoji)"
  source_file="$store/share/unicode/emoji/emoji-test.txt"
fi

version="$(sed -n 's/^# Version: //p' "$source_file" | head -n 1)"
version="${version:-unknown}"

mkdir -p "$(dirname "$out")"

{
  cat <<EOF
// Generated by tools/generate-emoji.sh from the Unicode emoji test file,
// version $version. Do not edit by hand.
//
// One tab-separated record per line -- character, name, group -- rather than an
// array of objects, because there are close to two thousand of them and the
// difference in the bundle is most of a hundred kilobytes. It is parsed on
// first use; see lib/emoji.ts.
//
// Skin-tone variants are left out. They are more than half the file and they
// all carry the same name as the emoji they modify, so every search would come
// back six deep in the same result.

export const EMOJI_DATA = \`\\
EOF

  awk -F' *; *' '
    /^# group:/ { group = substr($0, 10); next }
    # Data lines start with a code point. The status word also appears in the
    # file header, which is what the first test keeps out.
    /^[0-9A-F]/ && /; *fully-qualified/ {
      # The comment after the status holds the character and the name:
      #   1F600 ; fully-qualified # 😀 E1.0 grinning face
      hash = index($0, "#")
      rest = substr($0, hash + 2)

      split(rest, parts, " ")
      char = parts[1]

      # Skip the character and the "E<version>" field to reach the name.
      name = rest
      sub(/^[^ ]+ +E[0-9.]+ +/, "", name)

      if (name ~ /skin tone/) next
      print char "\t" name "\t" group
    }
  ' "$source_file"

  echo '`'
} > "$out"

printf 'wrote %s (%s entries, Unicode %s)\n' \
  "$out" "$(grep -c $'\t' "$out")" "$version"
